import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
      <Head>
        <title>Netflix - Watch TV Shows Online, Watch Movies Online.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {/* Banner */}
      </main>
    </div>
  )
}
